src/CSharpBbq.Web/Models/PlayerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CSharpBbq.Data.Model.Ladder;

namespace CSharpBbq.Web.Models
{
    public class PlayerViewModel
    {
        public Player Player { get; set; }
        public List<Match> Matches { get; set; }
        public int Wins { get; set; }
        public int Loses { get; set; }
        public string LastMatch { get; set; }
        public int CurrentRank { get; set; }
        public int Points { get; set; }
    }
}

src/CSharpBbq.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSharpBbq.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to ASP.NET MVC!";

            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

src/CSharpBbq.Web/Controllers/LadderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSharpBbq.Data.Model.Ladder;
using CSharpBbq.Web.Models;

namespace CSharpBbq.Web.Controllers
{
    public class LadderController : Controller
    {
        private IRepository repository = new LadderRepository();
        private IStandingRepository standingsRepository = new StandingRepository();


        //  [OutputCache(Duration = 32000, VaryByParam = "none")]
        public ActionResult Index()
        {
            return View("Home", CreateWeekData(repository.CurrentWeek().Id));
        }

        //   [OutputCache(Duration = 32000, VaryByParam = "none")]
        public ActionResult Rules()
        {
            return View();
        }

        public ActionResult FAQ()
        {
            return View();
        }
        // [OutputCache(Duration = 32000, VaryByParam = "none")]
        public ActionResult Legal()
        {
            return View();
        }

        //  [OutputCache(Duration = 32000, VaryByParam = "id")]
        public ActionResult Week(int id)
        {
            return View("Index", CreateWeekData(id));
        }
        private LadderWeekViewModel CreateWeekData(int id)
        {
            var data = new LadderWeekViewModel
            {
                LadderWeek = repository.LadderWeek(id),
                Matches = repository.Matches(id),
                Standings = (from c in standingsRepository.Standings(id)
                             select new PlayerViewModel { CurrentRank = c.Position, Player = c.Player }).ToList()
            };

            foreach (var p in data.Standings)
            {
                p.Matches = repository.PlayerMatches(p.Player.Id);
                p.Wins = p.Matches.Where(c => c.LadderWeek.WeekNumber <= data.LadderWeek.WeekNumber).Count(c => c.Winner.Id == p.Player.Id);
                p.Loses = p.Matches.Where(c => c.LadderWeek.WeekNumber <= data.LadderWeek.WeekNumber).Count(c => c.Looser.Id == p.Player.Id);
                p.LastMatch = p.Matches.Count > 0 ? p.Matches.Max(c => c.DateOfMatch).Value.ToShortDateString() : "No Match on Record";
                var winpoints = p.Matches.Where(c => c.LadderWeek.WeekNumber <= data.LadderWeek.WeekNumber && c.WinnerId == p.Player.Id).Sum(c => c.GetWinnerPoints());
                var loosePoints = p.Matches.Where(c => c.LadderWeek.WeekNumber <= data.LadderWeek.WeekNumber && c.LooserId == p.Player.Id).Sum(c => c.GetLooserPoints());
                p.Points = winpoints + loosePoints;

            }
            data.Standings = data.Standings.OrderByDescending(c => c.Points).ToList();

            return data;
        }

        public ActionResult SingleWeekResult()
        {
            return PartialView();
        }
        //   [OutputCache(Duration = 32000, VaryByParam = "id")]
        public ActionResult Player(int id)
        {
            var data = new PlayerViewModel { Player = repository.Player(id) };

            data.Matches = repository.PlayerMatches(id);
            data.Wins = data.Matches.Count(c => c.Winner.Id == data.Player.Id);
            data.Loses = data.Matches.Count(c => c.Looser.Id == data.Player.Id);
            data.LastMatch = data.Matches.Count > 0 ? data.Matches.Max(c => c.DateOfMatch).Value.ToShortDateString() : "No Match on Record";
            data.CurrentRank = standingsRepository.CurrentStandings().Where(c => c.Player.Id == id).First().Position;
            return View(data);
        }

        public ActionResult Weeks()
        {
            var lw = repository.LadderWeeks();

            return PartialView(lw);
        }
    }
}

src/CSharpBbq.Web/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSharpBbq.Data.Model.Ladder;
using CSharpBbq.Web.Models;

namespace CSharpBbq.Web.Controllers
{   
    public class PlayersController : Controller
    {
		private readonly IPlayerRepository playerRepository;

		// If you are using Dependency Injection, you can delete the following constructor
        public PlayersController() : this(new PlayerRepository())
        {
        }

        public PlayersController(IPlayerRepository playerRepository)
        {
			this.playerRepository = playerRepository;
        }

        //
        // GET: /Player/

        public ViewResult Index()
        {
            return View(playerRepository.GetAllPlayers(player => player.Standings));
        }

        //
        // GET: /Player/Details/5

        public ViewResult Details(int id)
        {
            return View(playerRepository.GetById(id));
        }

        //
        // GET: /Player/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Player/Create

        [HttpPost]
        public ActionResult Create(Player player)
        {
            if (ModelState.IsValid) {
                playerRepository.InsertOrUpdate(player);
                playerRepository.Save();
                return RedirectToAction("Index");
            } else {
				return View();
			}
        }
        
        //
        // GET: /Player/Edit/5
 
        public ActionResult Edit(int id)
        {
             return View(playerRepository.GetById(id));
        }

        //
        // POST: /Player/Edit/5

        [HttpPost]
        public ActionResult Edit(Player player)
        {
            if (ModelState.IsValid) {
                playerRepository.InsertOrUpdate(player);
                playerRepository.Save();
                return RedirectToAction("Index");
            } else {
				return View();
			}
        }

        //
        // GET: /Player/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View(playerRepository.GetById(id));
        }

        //
        // POST: /Player/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            playerRepository.Delete(id);
            playerRepository.Save();

            return RedirectToAction("Index");
        }
    }
}

src/CSharpBbq.Web/Views/Ladder/FAQ.cshtml
@{
    ViewBag.Title = "FAQ";
    Layout = "~/Views/Shared/_LayoutNoLinks.cshtml";
}

<h2>FAQ</h2>

src/CSharpBbq.Web/Views/Ladder/Home.cshtml
@model CSharpBbq.Web.Models.LadderWeekViewModel
@{
    ViewBag.Title = "Kerr Ladder - Home - Current Results";
}
<h2> Welcome to the ladder site. </h2>

<p> The Ladder is an ongoing tournament designed to help participants improve their racquetball skills, meet different players and enjoy the game. It is open to all Kerr YMCA members, from beginners to the best. You are guaranteed to play opponents at your skill level as people move up and down the ladder. The ladder will begin September 12th and run 10 weeks.  There is no set schedule for the matches. You can play at an agreed upon time between you and your opponent. 
</p>
<p> Ladder results will be posted outside the courts and will be available online at</p>

<p> Email me know if there is an issue with the site. </p>
 

src/CSharpBbq.Web/Views/Ladder/Index.cshtml
@model CSharpBbq.Web.Models.LadderWeekViewModel
@{
    ViewBag.Title = "Kerr Ladder - Week " + @Model.LadderWeek.WeekNumber.ToString();
}
  @{Html.RenderPartial("SingleWeekResult");}

src/CSharpBbq.Web/Views/Ladder/Legal.cshtml
@{
    ViewBag.Title = "Kerr Ladder - Legal";
    Layout = "";
}

<h1>Kerr YMCA RacquetBall Ladder</h1>
<h2>Assumption of Risk and Liability Release</h2>

<p>
<B>Release & Indemnification:</B> I hereby recognize and acknowledge that my &/or my child’s participation in recreational activities may 
involve bodily injury and/or emotional injury to myself and/or my child. In consideration of myself &/or my child being permitted to 
participate in such events, I for myself, my child, my heirs, my executors and administrators, hereby voluntarily and knowingly release, waive, and discharge Kerr YMCA, Ladder Participants, its officers, employees, and volunteers from any and all suits, claims or liability including negligence based on any injury except that may result from 
my &/or my child’s participation in activities.  In addition, I agree that I or my insurance will pay for medical hospitalization or any other expenses resulting from my &/or my child’s participation. 
</p>
<p>
<B>Emergency Treatment:</B> I hereby authorize Kerr YMCA & program staff to act on my &/or my child’s behalf in 
accordance with their best judgement in case of an emergency involving myself &/or my child, and agree to assume full responsibility for all expenses, medical, or otherwise, that may arise there from.  I understand that I or my insurance company will be billed for 
such emergency treatment. </p>
<p>
<B>Understanding:</B> By signing this assumption of risk, liability release, indemnification, and refund policy statement,  I acknowledge that I 
have read its contents and disclosure, that I understand its contents and disclosure and that I agree to its terms.</p>

<B>Signature________________________________       Date________________</B> 
</br></br> 
Please provide emergency contact informaiton below</br> </br> 

Name: ______________________________________________________________</br> 
</br> 
Email: ______________________________________________________________ </br>
 </br>
Phone Number:______________________________________________________________ </br>

src/CSharpBbq.Web/Views/Ladder/Player.cshtml
@model CSharpBbq.Web.Models.PlayerViewModel

@{
    ViewBag.Title = "Kerr Ladder - Player";
    Layout = "~/Views/Shared/_LayoutNoLinks.cshtml";
}

<h2>@Model.Player.Name</h2>
<div class="dash">
<div>Current Rank : @Model.CurrentRank</div>
<div>Wins : @Model.Wins</div>
<div>Loses : @Model.Loses</div>
<div>Last Match : @Model.LastMatch</div>


</div>


 @if (Model.Player.Standings.Count > 0)
 {
     
<table id="mytable" cellspacing="0" summary="Player Standings">
   <caption>Rankings per Week</caption>
    <tr>
        <th>
            Week
        </th>
        <th>
            Rank 
        </th>
    </tr>
    @foreach (var item in Model.Player.Standings)
    {
        <tr>
            <td>
              @Html.ActionLink(item.LadderWeek.WeekNumber.ToString(), "Week", new { id = item.LadderWeek.Id })
            </td>
            <td>@item.Position
            </td>
        </tr>
    }
</table>
}
 else
 { 
     <text>  ** No Standings Exist  </text>
 }

 </br>
  @if (Model.Matches.Count > 0)
 {
     
<table id="mytable" cellspacing="0" summary="Matches">
  <caption>@Model.Player.Name's Matches</caption>
    <tr>
        <th>
            Date
        </th>
        <th>
            Opponent 
        </th>
        <th>
            Result
        </th>
          
        <th>Gm 1
        </th>
        <th>Gm 2
        </th>
        <th>Gm 3
        </th>
    </tr>
    @foreach (var item in Model.Matches)
    {
        <tr>
            <td>@item.DateOfMatch.Value.ToShortDateString()
            </td>
            <td>@Html.ActionLink(Model.Player.Id == item.LooserId ? item.GetWinnerName() : item.GetLooserName(), "Player", new { id = Model.Player.Id == item.LooserId ? item.Winner.Id : item.Looser.Id  })
            </td>
            <td>@(Model.Player.Id == item.LooserId ? "Loss" : "Win")
            </td>
             <td nowrap="nowrap">
                @item.G1W - @item.G1L
            </td>
            <td nowrap="nowrap">
                @item.G2W - @item.G2L
            </td>
            <td nowrap="nowrap">
            @if (item.G3W.HasValue)
            {
                <text> @item.G3W - @item.G3L </text>
            }
            else
            {
                <text> </text>
            }
            </td>
        </tr>  
    }
</table>
 }
  else
  { 
     <text>  ** No Standings Exist  </text>
 }

src/CSharpBbq.Web/Views/Ladder/Rules.cshtml
@{
    ViewBag.Title = "Kerr Ladder - Rules";
    Layout = "~/Views/Shared/_LayoutNoLinks.cshtml";
}


<h2>Rule for the Ladder</h2>
<ul>
<li>All matches shall follow the <a href="http://www.usra.org/Rulebook.aspx" target="_blank"  >USRA official rules</a> of racquetball.</li>
<li>New players may join the ladder at any time.</li>
<li>All matches are played 2 games to 15, the third to 11. You win by 1 point!</li>
<li>Results are email to me at rb@csharpbbq.com</li>
<li>I will update the results Sunday night and send out to the group. Monday starts a new week.</li>
</ul>

<h2>Calculating Rankings</h2>
<ul>
<li>Rankings will be determined by earning points as follows</li>
<li>5 points are awarded for initaiting a challenge</li>
<li>If challenger defeats opponent ranked higher then them, they get 25 points</li>
<li>If challenger defeats opponent ranked equal or lower then them, they are awarded 20 points</li>
<li>You are awarded the points for your game including the tie breaker game to 11.</li>
<li>You can challenge 3 up or down the ladder. </li>
<li>You can only have 2 chanllenges per week. </li>
</ul>


For example if I challenge Jack and I'm ranked 5 and Jack is ranked 3 and I win 15-10, 10-15, 11-8 I would get 5 pts for the challenge, 25 for the 'W' and 26 for my points for a grand total of 66 points. This will start out messy but over 10 weeks the winner will surface.


<p>This is *NOT* a Y program. You must reserve courts through normal process and adhere to all Y rules<</p>

src/CSharpBbq.Web/Views/Ladder/SingleWeekResult.cshtml
@model CSharpBbq.Web.Models.LadderWeekViewModel
<h3>
    Results for Week Number @Model.LadderWeek.WeekNumber: @Model.LadderWeek.StertDate.ToShortDateString()
    - @Model.LadderWeek.EndDate.ToShortDateString()
</h3>
</br>
@if (Model.Standings.Count > 0)
{
     
    <table id="mytable" cellspacing="0" summary="Standings as of this week">
        <tr>
            <th>
                Rank
            </th>
            <th>
                Name
            </th>
            <th>
                Wins
            </th>
              <th>
                Loses
            </th>
               <th>
                Points
            </th>
        </tr>
        @foreach (var item in Model.Standings)
        {
            <tr>
                <td>@item.CurrentRank
                </td>
                <td>
                    @Html.ActionLink(item.Player.Name, "Player", new { id = item.Player.Id })
                </td>
                 <td>@item.Wins
                </td>
                <td>@item.Loses
                </td>
                <td>@item.Points
                </td>
            </tr>
        }
    </table>
}
else
{ 
    <text> ** Results for this week have been recorded </text>
}
<br>
@if (Model.Matches.Count > 0)
{
 
    foreach (var item in Model.Matches)
    {
    <div class="results">
        <div>@item.DateOfMatch.Value.ToShortDateString()</div>
        <div>@Html.ActionLink(@item.GetWinnerName(), "Player", new { id = item.Winner.Id }) defeated
            @Html.ActionLink(@item.GetLooserName(), "Player", new { id = item.Looser.Id })
            @item.G1W-@item.G1L, @item.G2W-@item.G2L
            @if (item.G3L.HasValue)
            {
                <text> @item.G3W-@item.G3L </text>
            }
        </div>
    </div>
    }
}
else
{
    <text>** No Matches for this week</text>
}
<cite> * Challenger </cite>

src/CSharpBbq.Web/Views/Ladder/Weeks.cshtml
@model IEnumerable<CSharpBbq.Data.Model.Ladder.LadderWeek>
@foreach (var item in Model)
{
    if (item.Standings.Count > 0)
    {
    @Html.ActionLink("Week " + item.WeekNumber, "Week", "Ladder", new { id = item.Id }, null)
    }
    else
    { 
    <text>Week @item.WeekNumber</text>
    }
<text><br></text>
}