src/CSharpBbq.Web/Controllers/StandingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSharpBbq.Data.Model.Ladder;
using CSharpBbq.Web.Models;

namespace CSharpBbq.Web.Controllers
{
    public class StandingsController : Controller
    {
        private readonly IStandingRepository standingRepository;
        private readonly ILadderWeekRepository ladderWeekRepository;
        private IRepository repository = new LadderRepository();

        // If you are using Dependency Injection, you can delete the following constructor
        public StandingsController()
            : this(new StandingRepository(), new LadderRepository(), new LadderWeekRepository())
        {
        }

        public StandingsController(IStandingRepository standingRepository, IRepository repository, ILadderWeekRepository ladderWeekRepository)
        {
            this.standingRepository = standingRepository;
            this.repository = repository;
            this.ladderWeekRepository = ladderWeekRepository;

        }

        //
        // GET: /Standing/

        public ViewResult Index()
        {
            return View(standingRepository.GetAllStandings());
        }

        //
        // GET: /Standing/Details/5

        public ViewResult Details(int id)
        {
            return View(standingRepository.GetById(id));
        }

        //
        // GET: /Standing/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Standing/Create

        [HttpPost]
        public ActionResult Create(Standing standing)
        {
            if (ModelState.IsValid)
            {
                standingRepository.InsertOrUpdate(standing);
                standingRepository.Save();
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        //
        // GET: /Standing/Edit/5

        public ActionResult Edit(int id)
        {
            return View(id);
        }

        //
        // POST: /Standing/Edit/5

        [HttpPost]
        public ActionResult Edit(Standing standing)
        {
            if (ModelState.IsValid)
            {
                standingRepository.InsertOrUpdate(standing);



                standingRepository.Save();
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
          
        }

        //
        // GET: /Standing/Delete/5

        public ActionResult Delete(int id)
        {
            return View(standingRepository.GetById(id));
        }

        public ActionResult CreateNewWeek(int id)
        {
            var currentWeek = repository.CurrentWeek();
            var newStandings = GetNewStandings(currentWeek.WeekNumber, id);

            var position = 1;
            foreach (var s in newStandings.OrderByDescending(g => g.TotalPoints))
            {
                s.Position = position;
                position++;
                standingRepository.InsertOrUpdate(s);
            }

            standingRepository.Save();

            currentWeek.IsCurrent = false;
            ladderWeekRepository.InsertOrUpdate(currentWeek);

            var nextWeek = ladderWeekRepository.GetById(id);
            nextWeek.IsCurrent = true;
            ladderWeekRepository.InsertOrUpdate(nextWeek);

            return View("Edit", id);
        }
        private List<Standing> GetNewStandings(int currentWeekNumber, int nextWeekId)
        {
            var matches = repository.GetAllMatches(c => c.LadderWeek, c => c.Winner, c => c.Looser);

            var currentStandings = standingRepository.CurrentStandings();
            var newStandings = new List<Standing>();
            foreach (var currentStanding in currentStandings)
            {
                var winpoints = matches.Where(c => c.LadderWeek.WeekNumber <= currentWeekNumber && c.WinnerId == currentStanding.PlayerId).Sum(c => c.GetWinnerPoints());
                var loosePoints = matches.Where(c => c.LadderWeek.WeekNumber <= currentWeekNumber && c.LooserId == currentStanding.PlayerId).Sum(c => c.GetLooserPoints());
                newStandings.Add(new Standing { LadderWeekId = nextWeekId, PlayerId = currentStanding.PlayerId, TotalPoints = winpoints + loosePoints });
            }
            return newStandings;
        }
        //
        // POST: /Standing/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            standingRepository.Delete(id);
            standingRepository.Save();

            return RedirectToAction("Index");
        }


        public JsonResult GridData(int ladderWeekId, int rows, int page)
        {
            var count = standingRepository.GetAllStandings().Count();
            var pageData = standingRepository.GetAllStandings(c => c.Player).Where(c => c.LadderWeekId == ladderWeekId).Select(c => new { StandingId = c.Id, c.Player.Name, c.Position, c.PlayerId, c.LadderWeekId }).OrderBy(c => c.Position);
            return Json(new
                            {
                                page = page,
                                records = count,
                                rows = pageData
                            }, JsonRequestBehavior.AllowGet);
        }

    }
}

src/CSharpBbq.Web/Views/Standings/Create.cshtml
@model CSharpBbq.Data.Model.Ladder.Standing

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutNoLinks.cshtml";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Standing</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.LadderWeekId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LadderWeekId)
            @Html.ValidationMessageFor(model => model.LadderWeekId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PlayerId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PlayerId)
            @Html.ValidationMessageFor(model => model.PlayerId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Position)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Position)
            @Html.ValidationMessageFor(model => model.Position)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/CSharpBbq.Web/Views/Standings/Delete.cshtml
@model CSharpBbq.Data.Model.Ladder.Standing

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutNoLinks.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Standing</legend>

    <div class="display-label">LadderWeekId</div>
    <div class="display-field">@Model.LadderWeekId</div>

    <div class="display-label">PlayerId</div>
    <div class="display-field">@Model.PlayerId</div>

    <div class="display-label">Position</div>
    <div class="display-field">@Model.Position</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

src/CSharpBbq.Web/Views/Standings/Details.cshtml
@model CSharpBbq.Data.Model.Ladder.Standing

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutNoLinks.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>Standing</legend>

    <div class="display-label">LadderWeekId</div>
    <div class="display-field">@Model.LadderWeekId</div>

    <div class="display-label">PlayerId</div>
    <div class="display-field">@Model.PlayerId</div>

    <div class="display-label">Position</div>
    <div class="display-field">@Model.Position</div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/CSharpBbq.Web/Views/Standings/Edit.cshtml
@model int
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutNoLinks.cshtml";
}
<h2>
    Edit</h2>
<link href="@Url.Content("~/content/jquery-ui-1.8.11.custom.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/content/ui.jqgrid.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/ext/jquery-1.4.2.min.js")" type="text/javascript" ></script>
<script src="@Url.Content("~/Scripts/ext/grid.locale-en.js")" type="text/javascript" ></script>
<script src="@Url.Content("~/Scripts/ext/jquery.jqGrid.min.js")" type="text/javascript" ></script>
<script type="text/javascript">

    $(function () {
        $("#ajaxGrid").jqGrid({
            url: '@Url.Action("GridData","Standings", new {ladderWeekId = Model} )',
            datatype: "json",
            jsonReader: { repeatitems: false, id: "StandingId" },
            colNames: ['StandingId', 'Position', 'Name', "PlayerId", "LadderWeekId"],
            colModel: [
             { name: 'StandingId', editable: true, sortable: false, hidden: true },
             { name: 'Position', editable: true, sortable: true, hidden: false },
             { name: 'Name', editable: false, sortable: false, hidden: false },
             { name: 'PlayerId', editable: true, sortable: false, hidden: true },
             { name: 'LadderWeekId', editable: true, sortable: false, hidden: true }
         ],
            pager: '#ajaxGridPager',
            rowNum: 25,
            width: '560px',
            height: '450px'
        });


        jQuery("#ajaxGrid").jqGrid('navGrid', '#ajaxGridPager',
         { search: false, refresh: false },
        //Edit Options
         {url: '@Url.Action("Edit")', closeAfterEdit: true },
        //Add Options
         {url: '@Url.Action("Create")', closeAfterAdd: true },
        //Delete Options
         {url: '@Url.Action("Delete")' }
     );

    });
</script>
<table id="ajaxGrid">
</table>
<div id="ajaxGridPager">
</div>

src/CSharpBbq.Web/Views/Standings/Index.cshtml
@model IEnumerable<CSharpBbq.Data.Model.Ladder.Standing>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutNoLinks.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th></th>
        <th>
            LadderWeekId
        </th>
        <th>
            PlayerId
        </th>
        <th>
            Position
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
        <td>
            @item.LadderWeekId
        </td>
        <td>
            @item.PlayerId
        </td>
        <td>
            @item.Position
        </td>
    </tr>
}

</table>