src/CSharpBbq.Web/Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSharpBbq.Data.Model.Ladder;
using CSharpBbq.Web.Models;

namespace CSharpBbq.Web.Controllers
{
    public class MatchesController : Controller
    {
        private readonly IPlayerRepository playerRepository;
        private readonly IMatchRepository matchRepository;
        private readonly IRepository ladderRepository;
        private IStandingRepository standingsRepository = new StandingRepository();

        // If you are using Dependency Injection, you can delete the following constructor
        public MatchesController()
            : this(new PlayerRepository(), new MatchRepository(), new LadderRepository())
        {
        }

        public MatchesController(IPlayerRepository playerRepository, IMatchRepository matchRepository, IRepository ladderRepository)
        {
            this.playerRepository = playerRepository;
            this.matchRepository = matchRepository;
            this.ladderRepository = ladderRepository;
        }

        //
        // GET: /Match/

        public ViewResult Index()
        {
            return View(ladderRepository.GetAllMatches(match => match.Winner, match => match.Looser, match => match.LadderWeek));
        }
        public ViewResult IndexReadOnly()
        {
            return View(ladderRepository.GetAllMatches(match => match.Winner, match => match.Looser, match => match.LadderWeek).OrderBy(c => c.DateOfMatch));
        }

        //
        // GET: /Match/Details/5

        public ViewResult Details(int id)
        {
            return View(ladderRepository.GetMatchById(id));
        }

        //
        // GET: /Match/Create

        public ActionResult Create()
        {
            ViewBag.PossibleWinners = playerRepository.GetAllPlayers();
            ViewBag.PossibleLoosers = playerRepository.GetAllPlayers();
            ViewBag.PossibleLadderWeeks = ladderRepository.LadderWeeks();
            return View();
        }

        //
        // POST: /Match/Create

        [HttpPost]
        public ActionResult Create(Match match)
        {
            match.WinnerRank = (short)this.ladderRepository.GetPlayerStanding(match.LadderWeekId, match.WinnerId);
            match.LooserRank = (short)this.ladderRepository.GetPlayerStanding(match.LadderWeekId, match.LooserId);

            if (ModelState.IsValid)
            {
                matchRepository.InsertOrUpdate(match);
                matchRepository.Save();
            //    UpdateStandings(match.LadderWeekId, match.LadderWeekId);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.PossibleWinners = playerRepository.GetAllPlayers();
                ViewBag.PossibleLoosers = playerRepository.GetAllPlayers();
                ViewBag.PossibleLadderWeeks = ladderRepository.LadderWeeks();
                return View();
            }
        }

        //private void UpdateStandings(int weekNumber, int weekId)
        //{
        //    var standings = (from c in standingsRepository.Standings(weekId)
        //                     select new PlayerViewModel { CurrentRank = c.Position, Player = c.Player }).ToList();

        //    foreach (var p in standings)
        //    {
        //        p.Matches = ladderRepository.PlayerMatches(p.Player.Id);
        //        p.Wins = p.Matches.Where(c => c.LadderWeek.WeekNumber <= weekNumber).Count(c => c.Winner.Id == p.Player.Id);
        //        p.Loses = p.Matches.Where(c => c.LadderWeek.WeekNumber <= weekNumber).Count(c => c.Looser.Id == p.Player.Id);
        //        p.LastMatch = p.Matches.Count > 0 ? p.Matches.Max(c => c.DateOfMatch).Value.ToShortDateString() : "No Match on Record";
        //        var winpoints = p.Matches.Where(c => c.LadderWeek.WeekNumber <= weekNumber && c.WinnerId == p.Player.Id).Sum(c => c.GetWinnerPoints());
        //        var loosePoints = p.Matches.Where(c => c.LadderWeek.WeekNumber <= weekNumber && c.LooserId == p.Player.Id).Sum(c => c.GetLooserPoints());
        //        p.Points = winpoints + loosePoints;
        //    }

        //    standings.OrderByDescending(c => c.Points).ToList();

        //    var i = 1;
        //    foreach (var p in standings)
        //    {
        //        standingsRepository.Standings

        //        p.CurrentRank = i;
        //        i++;
        //        standingsRepository.InsertOrUpdate(p);
        //    }
        //}

        //
        // GET: /Match/Edit/5

        public ActionResult Edit(int id)
        {
            ViewBag.PossibleWinners = playerRepository.GetAllPlayers();
            ViewBag.PossibleLoosers = playerRepository.GetAllPlayers();
            ViewBag.PossibleLadderWeeks = ladderRepository.LadderWeeks();
            return View(ladderRepository.GetMatchById(id));
        }

        //
        // POST: /Match/Edit/5

        [HttpPost]
        public ActionResult Edit(Match match)
        {
            if (ModelState.IsValid)
            {
                matchRepository.InsertOrUpdate(match);
                matchRepository.Save();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.PossibleWinners = playerRepository.GetAllPlayers();
                ViewBag.PossibleLoosers = playerRepository.GetAllPlayers();
                return View();
            }
        }

        //
        // GET: /Match/Delete/5

        public ActionResult Delete(int id)
        {
            return View(ladderRepository.GetMatchById(id));
        }

        //
        // POST: /Match/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            matchRepository.Delete(id);
            matchRepository.Save();

            return RedirectToAction("Index");
        }
    }
}

src/CSharpBbq.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>
                    Kerr YMCA RacquetBall</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    @if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("LadderUser"))
                    {
                         <li>@Html.ActionLink("Ladder", "Ladder", "Rules")</li>
                    }
                    @if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("Administrators"))
                    {
                       <li>@Html.ActionLink("Ladder-Admin", "LadderAdmin", "Index")</li>
                    }
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

src/CSharpBbq.Web/Views/Shared/_LayoutNoLinks.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/ladder.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.6.3.min.js")" type="text/javascript" ></script>
    <script src="../../Scripts/ext/jquery-ui-1.8.11.custom.min.js" type="text/javascript"></script>
    <!-- <script type="text/javascript">
         $(function() {
             $(".datePicker").datepicker({ showOn: 'both', buttonImage: "/Content/images/calendar.gif" });
         });
     </script>-->
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-22500538-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
</head>
<body>
    <!-- Begin Wrapper -->
    <div id="wrapper">
        <!-- Begin Header -->
        <div id="header">
            <h1>
                Kerr YMCA Racquetball</h1>
        </div>
        <!-- End Header -->
        <!-- Begin Faux Columns -->
        <div id="faux">
            <!-- Begin Left Column -->
            <div id="leftcolumn">
                @Html.ActionLink("Home", "Index", "Ladder")<br>
                @Html.ActionLink("Rules", "Rules", "Ladder")<br>
                   @Html.ActionLink("FAQ", "FAQ", "Ladder")<br>
                @Html.ActionLink("All Matches", "IndexReadOnly", "Matches")<br>
                @Html.Action("Weeks", "Ladder")<br>
                <a href="ladder\Legal">Waiver</a>
            </div>
            <!-- End Left Column -->
            <!-- Begin Right Column -->
            <div id="rightcolumn">
                @RenderBody()
                <div class="clear">
                </div>
            </div>
            <!-- End Right Column -->
            <div class="clear">
            </div>
        </div>
        <!-- End Faux Columns -->
        <!-- Begin Footer -->
        <div id="footer">
            <a href="mailto:rb@csharpbbq.com">Email</a> me with questions
        </div>
    </div>
    <!-- End Footer -->
    </div>
    <!-- End Wrapper -->
</body>
</html>

src/CSharpBbq.Web/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}